# Generated by Django 3.2.13 on 2023-04-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastestUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('image_url_link', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('latest_update_table_id', models.IntegerField(default=None, null=True)),
                ('latest_update_table_name', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
    ]
