# Generated by Django 3.2.13 on 2023-10-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matric_number',
            field=models.CharField(default='', max_length=1000, unique=True),
        ),
    ]
