# Generated by Django 3.2.13 on 2023-05-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesforgalleryv2',
            name='caption',
            field=models.TextField(default=' '),
        ),
    ]
