# Generated by Django 3.2.13 on 2023-05-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_imagesforgalleryv2_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportprojectincash',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
