# Generated by Django 3.2.13 on 2023-04-25 12:03

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReissuanceOfCertForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=200)),
                ('cac_reg_number', models.CharField(max_length=200)),
                ('tax_identification_number', models.CharField(max_length=200)),
                ('man_reg_number', models.CharField(max_length=200)),
                ('company_official_email', models.CharField(max_length=200)),
                ('company_official_website', models.CharField(max_length=200)),
                ('corporate_addresse', models.CharField(max_length=200)),
                ('other_factory_location', models.JSONField(default=dict)),
                ('products_manufactured', models.JSONField(default=dict)),
                ('list_of_imported_materials_used_in_production', models.JSONField(default=dict)),
                ('list_of_local_materials_used_in_production', models.JSONField(default=dict)),
                ('managing_director_email', models.EmailField(max_length=254)),
                ('managing_director_phone', models.CharField(max_length=200)),
                ('chief_finance_officer_phone', models.CharField(max_length=200)),
                ('chief_finance_officer_email', models.CharField(max_length=200)),
                ('head_of_admin_phone', models.CharField(max_length=200)),
                ('head_of_admin_email', models.CharField(max_length=200)),
                ('head_of_corporate_affair_phone', models.CharField(max_length=200)),
                ('head_of_corporate_affair_email', models.CharField(max_length=200)),
                ('officer_handling_man_issues_in_your_company_phone', models.CharField(max_length=200)),
                ('officer_handling_man_issues_in_your_company_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyTurnOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('attachment', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='attachment_finicial_statement/%d/')),
                ('reissuance_of_cert_form', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.reissuanceofcertform')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateOnProductsManufactured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_recent_financial_statement', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='most_recent_financial_statement/%d/')),
                ('product_update_inspection_report', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='product_update_inspection_report/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('disapprove', 'Disapprove')], default='pending', max_length=300)),
                ('member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.memeber')),
            ],
        ),
        migrations.CreateModel(
            name='ReissuanceOfCertServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('disapprove', 'Disapprove')], default='pending', max_length=300)),
                ('member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.memeber')),
                ('reissuance_of_cert_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.reissuanceofcertform')),
            ],
        ),
        migrations.CreateModel(
            name='MergerOfMemberCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_requesting_merger_of_companies', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='letter_requesting_merger_of_companies/%d/')),
                ('most_recent_audited_finicial_statement', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='most_recent_audited_finicial_statement/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('disapprove', 'Disapprove')], default='pending', max_length=300)),
                ('member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.memeber')),
            ],
        ),
        migrations.CreateModel(
            name='LossOfCertificateServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affidavit_from_court_of_loss_of_cert', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='affidavit_from_court_of_loss_of_cert/')),
                ('amount_to_be_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year_one_audited_finacial_statements', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='year_one_audited_finacial_statements/%d/')),
                ('year_two_audited_finacial_statements', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='year_one_audited_finacial_statements/%d/')),
                ('certificate_of_incorporation', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificate_of_incorporation/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('disapprove', 'Disapprove')], default='pending', max_length=300)),
                ('member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.memeber')),
                ('reissuance_of_cert_form', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.reissuanceofcertform')),
            ],
        ),
        migrations.CreateModel(
            name='DeactivationOfMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_requesting_deactivation', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='letter_requesting_deactivation/%d/')),
                ('original_membership_certificate', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='original_membership_certificate/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('disapprove', 'Disapprove')], default='pending', max_length=300)),
                ('member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.memeber')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeOfName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_membership_certificate', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='original_membership_certificate/%d/')),
                ('amount_to_be_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year_one_audited_finacial_statements', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='year_one_audited_finacial_statements/%d/')),
                ('year_two_audited_finacial_statements', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='year_one_audited_finacial_statements/%d/')),
                ('certificate_of_incorporation', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificate_of_incorporation/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('disapprove', 'Disapprove')], default='pending', max_length=300)),
                ('member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.memeber')),
                ('reissuance_of_cert_form', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.reissuanceofcertform')),
            ],
        ),
        migrations.CreateModel(
            name='AllMembershipCertificatesAboutConcernedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_certificates', models.TextField()),
                ('document', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='all_membership_certificates_about_concerned_company/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('disapprove', 'Disapprove')], default='pending', max_length=300)),
                ('merger_of_member_companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.mergerofmembercompanies')),
            ],
        ),
        migrations.CreateModel(
            name='ActivationOfDeactivatedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_most_recent_audited_financial_statement', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='submit_most_recent_audited_financial_statement/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('disapprove', 'Disapprove')], default='pending', max_length=300)),
                ('member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.memeber')),
            ],
        ),
    ]
