# Generated by Django 3.2.13 on 2023-04-25 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetPropectiveMembershipRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('propective_members_text_fields', models.JSONField(default=None, null=True)),
                ('propective_members_file_fields', models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectiveMemberFormTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationAmountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectiveMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=600)),
                ('telephone_number', models.CharField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
                ('addresse', models.TextField()),
                ('has_paid', models.BooleanField(default=False)),
                ('paystack', models.CharField(max_length=300)),
                ('paystack_key', models.CharField(default='.', max_length=300)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('application_status', models.CharField(choices=[('approval_in_progress', 'Approval In Progress'), ('approval_in_principle_granted', 'Approval In Principle Granted'), ('final_approval', 'Final Approval')], default='approval_in_progress', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectiveMemberFormTwoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('file', models.FileField(upload_to='prospectivemember_file/%m/')),
                ('form_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospectivemember.prospectivememberformtwo')),
            ],
        ),
        migrations.AddField(
            model_name='prospectivememberformtwo',
            name='prospective_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prospectivemember.prospectivememberprofile'),
        ),
        migrations.CreateModel(
            name='ProspectiveMemberFormOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField(default=dict)),
                ('prospective_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prospectivemember.prospectivememberprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ManProspectiveMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=600)),
                ('telephone_number', models.CharField(max_length=600)),
                ('cac_registration_number', models.TextField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('corporate_office_addresse', models.TextField()),
                ('has_paid', models.BooleanField(default=False)),
                ('paystack', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('application_status', models.CharField(choices=[('approval_in_progress', 'Approval In Progress'), ('approval_in_principle_granted', 'Approval In Principle Granted'), ('final_approval', 'Final Approval')], default='approval_in_progress', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManProspectiveMemberFormTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_affairs_commision', models.FileField(upload_to='corporate_affairs_commision/')),
                ('letter_of_breakdown_of_payment_and_docs_attached', models.FileField(upload_to='letter_of_breakdown_of_payment_and_docs_attached/')),
                ('first_year_of_buisness_plan', models.FileField(upload_to='first_year_of_buisness_plan/')),
                ('second_year_of_buisness_plan', models.FileField(upload_to='second_year_of_buisness_plan/')),
                ('photocopy_of_your_reciept_issued_on_purchase_of_applicant_form', models.FileField(upload_to='photocopy_of_your_reciept_issued_on_purchase_of_applicant_form/')),
                ('prospective_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prospectivemember.manprospectivememberprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ManProspectiveMemberFormOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cac_registration_number', models.TextField(max_length=600)),
                ('name_of_company', models.CharField(max_length=600)),
                ('tax_identification_number', models.TextField()),
                ('corporate_office_addresse', models.TextField()),
                ('office_bus_stop', models.TextField()),
                ('office_city', models.TextField()),
                ('office_lga', models.TextField()),
                ('office_state', models.CharField(max_length=300)),
                ('postal_addresse', models.CharField(max_length=300)),
                ('telephone', models.CharField(max_length=13)),
                ('email_addresse', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('factoru_details', models.TextField()),
                ('legal_status_of_company', models.CharField(max_length=100)),
                ('number_of_female_expatriates', models.IntegerField(default=0)),
                ('number_of_male_expatriates', models.IntegerField(default=0)),
                ('number_of_male_permanent_staff', models.IntegerField(default=0)),
                ('number_of_female_permanent_staff', models.IntegerField(default=0)),
                ('local_share_capital', models.TextField(default='.')),
                ('foreign_share_capital', models.TextField(default='.')),
                ('ownership_structure_equity_local', models.TextField(default='.')),
                ('ownership_structure_equity_foregin', models.TextField(default='.')),
                ('total_value_of_land_asset', models.TextField(default='.')),
                ('total_value_of_building_asset', models.TextField(default='.')),
                ('total_value_of_other_asset', models.TextField(default='.')),
                ('installed_capacity', models.TextField(default='.')),
                ('current_sales_turnover', models.TextField(default='.')),
                ('projected_sales_turnover', models.TextField(default='.')),
                ('are_your_product_exported', models.TextField(default='.')),
                ('company_contact_infomation', models.TextField(default='.')),
                ('designation', models.TextField(default='.')),
                ('name_of_md_or_ceo_of_company', models.TextField(default='.')),
                ('selectdate_of_registration', models.DateField(default=None, null=True)),
                ('upload_signature', models.ImageField(default=None, null=True, upload_to='upload_signature/%m/')),
                ('all_roduct_manufactured', models.JSONField(default=list)),
                ('all_raw_materials_used', models.JSONField(default=list)),
                ('prospective_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prospectivemember.manprospectivememberprofile')),
            ],
        ),
    ]
