# Generated by Django 3.2.13 on 2023-04-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manprospectivememberprofile',
            name='has_paid_subcription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manprospectivememberprofile',
            name='subcription_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
