# Generated by Django 3.2.13 on 2023-05-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0004_remark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
