# Generated by Django 3.2.13 on 2023-05-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0006_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='manprospectivememberprofile',
            name='admin',
            field=models.TextField(default='no remark from admin'),
        ),
    ]
