# Generated by Django 3.2.13 on 2023-05-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0007_manprospectivememberprofile_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='manprospectivememberprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
