# Generated by Django 3.2.13 on 2023-05-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0009_alter_manprospectivememberprofile_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manprospectivememberformone',
            name='capacity_type',
            field=models.CharField(choices=[('kg', 'Kg'), ('ton', 'Ton')], default='kg', max_length=20),
        ),
    ]
