# Generated by Django 3.2.13 on 2023-05-22 09:57

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0011_auto_20230522_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manprospectivememberformtwo',
            name='corporate_affairs_commision',
            field=models.FileField(default=None, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='corporate_affairs_commision/'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformtwo',
            name='first_year_of_buisness_plan',
            field=models.FileField(default=None, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='first_year_of_buisness_plan/'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformtwo',
            name='letter_of_breakdown_of_payment_and_docs_attached',
            field=models.FileField(default=None, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='letter_of_breakdown_of_payment_and_docs_attached/'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformtwo',
            name='photocopy_of_your_reciept_issued_on_purchase_of_applicant_form',
            field=models.FileField(default=None, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='photocopy_of_your_reciept_issued_on_purchase_of_applicant_form/'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformtwo',
            name='second_year_of_buisness_plan',
            field=models.FileField(default=None, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='second_year_of_buisness_plan/'),
        ),
    ]
