# Generated by Django 3.2.13 on 2023-05-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0012_auto_20230522_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manprospectivememberformtwo',
            old_name='photocopy_of_your_reciept_issued_on_purchase_of_applicant_form',
            new_name='photo_copy',
        ),
    ]
