# Generated by Django 3.2.13 on 2023-05-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0013_rename_photocopy_of_your_reciept_issued_on_purchase_of_applicant_form_manprospectivememberformtwo_ph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manprospectivememberformtwo',
            old_name='photo_copy',
            new_name='photocopy_of_your_reciept_issued_on_purchase_of_applicant_form',
        ),
    ]
