# Generated by Django 3.2.13 on 2023-06-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0015_alter_manprospectivememberprofile_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manprospectivememberprofile',
            name='has_sent_acknowledgement',
            field=models.BooleanField(default=False),
        ),
    ]
