# Generated by Django 3.2.13 on 2023-06-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0016_manprospectivememberprofile_has_sent_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='manprospectivememberprofile',
            name='inspection_factory_file',
            field=models.FileField(default=None, null=True, upload_to='man_inspection/%d/'),
        ),
    ]
