# Generated by Django 3.2.13 on 2023-07-03 11:08

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0017_manprospectivememberprofile_inspection_factory_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manprospectivememberformtwo',
            name='corporate_affairs_commision',
            field=models.FileField(default=None, max_length=700, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='commision/'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformtwo',
            name='first_year_of_buisness_plan',
            field=models.FileField(default=None, max_length=700, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='buisness_plan/'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformtwo',
            name='letter_of_breakdown_of_payment_and_docs_attached',
            field=models.FileField(default=None, max_length=700, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='attached/'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformtwo',
            name='photocopy_of_your_reciept_issued_on_purchase_of_applicant_form',
            field=models.FileField(default=None, max_length=700, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='applicant_form2/'),
        ),
        migrations.AlterField(
            model_name='manprospectivememberformtwo',
            name='second_year_of_buisness_plan',
            field=models.FileField(default=None, max_length=700, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='buisness_plan2/'),
        ),
    ]
