# Generated by Django 3.2.13 on 2023-07-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivemember', '0018_auto_20230703_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='manprospectivememberprofile',
            name='executive_email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
