# Generated by Django 3.2.13 on 2023-12-20 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersReIssuanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=500)),
                ('cac_number', models.CharField(max_length=500)),
                ('tax_identification_number', models.CharField(max_length=500)),
                ('man_reg_number', models.CharField(max_length=10)),
                ('company_official_email', models.EmailField(max_length=254)),
                ('corporate_addresse', models.TextField()),
                ('ceo_name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=15)),
                ('chief_finace_officer', models.CharField(max_length=40)),
                ('chief_finace_officer_phone_number', models.CharField(max_length=15)),
                ('head_of_coporate', models.CharField(max_length=40)),
                ('head_of_coporate_phone_number', models.CharField(max_length=15)),
                ('officer_handling_man', models.CharField(max_length=40)),
                ('officer_handling_man_phone_number', models.CharField(max_length=15)),
                ('member', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.memeber')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyTurnOVer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_one', models.DateField(blank=True, default=None, null=True)),
                ('date_two', models.DateField(blank=True, default=None, null=True)),
                ('file_fordate_one', models.FileField(blank=True, default=None, null=True, upload_to='file_fordate_one/%d/')),
                ('file_fordate_two', models.FileField(blank=True, default=None, null=True, upload_to='file_fordate_two/%d/')),
                ('members_reissuanceform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membershipservice.membersreissuanceform')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateOnProductManufactured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('most_recent_finicial_statement', models.FileField(blank=True, default=None, null=True, upload_to='most_recent_finicial_statement/%d/')),
                ('product_report_for_branch_inspection', models.FileField(blank=True, default=None, null=True, upload_to='product_report_for_branch_inspection/%d/')),
                ('note', models.TextField(default='')),
                ('members_reissuanceform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membershipservice.membersreissuanceform')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateFactoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('most_recent_finicial_statement', models.FileField(blank=True, default=None, null=True, upload_to='most_recent_finicial_statement/%d/')),
                ('product_report_for_branch_inspection', models.FileField(blank=True, default=None, null=True, upload_to='product_report_for_branch_inspection/%d/')),
                ('note', models.TextField(default='')),
                ('members_reissuanceform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membershipservice.membersreissuanceform')),
            ],
        ),
        migrations.CreateModel(
            name='RenewalOFCertWithThatChangeThierOriginialName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_change_of_name_cert', models.FileField(upload_to='submit_change_of_name_cert/%d/')),
                ('bank_teller_of_payment', models.FileField(upload_to='bank_teller_of_payment/%d/')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('note', models.TextField(default='')),
                ('certificate_which_expired_on_thirtyone', models.FileField(blank=True, default=None, null=True, upload_to='certificate_which_expired_on31/%d/')),
                ('copy_of_certificate_incoporation', models.FileField(blank=True, default=None, null=True, upload_to='copy_of_certificate_incoporation/%d/')),
                ('audited_finicial_statement_one', models.FileField(blank=True, default=None, null=True, upload_to='audited_finicial_statement_one/%d/')),
                ('audited_finicial_statement_two', models.FileField(blank=True, default=None, null=True, upload_to='audited_finicial_statement_two/%d/')),
                ('members_reissuanceform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membershipservice.membersreissuanceform')),
            ],
        ),
        migrations.CreateModel(
            name='RenewalOFCertWithCompaniesThatHave2Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('members_reissuanceform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membershipservice.membersreissuanceform')),
            ],
        ),
        migrations.CreateModel(
            name='MergerOfMemberCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('letter_requesting_merge', models.FileField(blank=True, default=None, null=True, upload_to='letter_requesting_merge/%d/')),
                ('most_recent_finicial_statement', models.FileField(blank=True, default=None, null=True, upload_to='most_recent_finicial_statement/%d/')),
                ('note', models.TextField(default='')),
                ('members_reissuanceform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membershipservice.membersreissuanceform')),
            ],
        ),
        migrations.CreateModel(
            name='CompaniesThatlostManCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('bank_teller_of_payment', models.FileField(upload_to='bank_teller_of_payment/%d/')),
                ('affidavit_from_court', models.FileField(upload_to='affidavit_from_court/%d/')),
                ('note', models.TextField(default='')),
                ('certificate_which_expired_on_thirtyone', models.FileField(blank=True, default=None, null=True, upload_to='certificate_which_expired_on31/%d/')),
                ('copy_of_certificate_incoporation', models.FileField(blank=True, default=None, null=True, upload_to='copy_of_certificate_incoporation/%d/')),
                ('audited_finicial_statement_one', models.FileField(blank=True, default=None, null=True, upload_to='audited_finicial_statement_one/%d/')),
                ('audited_finicial_statement_two', models.FileField(blank=True, default=None, null=True, upload_to='audited_finicial_statement_two/%d/')),
                ('members_reissuanceform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membershipservice.membersreissuanceform')),
            ],
        ),
        migrations.CreateModel(
            name='CompaniesDeactivationActivationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(default='')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('letter_request_for_activation_or_deactivation', models.FileField(blank=True, default=None, null=True, upload_to='letter_request_for_activation_or_deactivation/%d/')),
                ('submit_original_membership_cert', models.FileField(blank=True, default=None, null=True, upload_to='submit_original_membership_cert/%d/')),
                ('members_reissuanceform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membershipservice.membersreissuanceform')),
            ],
        ),
    ]
