# Generated by Django 3.2.13 on 2023-06-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membershipservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersreissuanceform',
            name='imported_raw_materials',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='membersreissuanceform',
            name='locally_sourced_raw_materials',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='membersreissuanceform',
            name='plants',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='membersreissuanceform',
            name='products_manufactured',
            field=models.JSONField(default=list),
        ),
    ]
