# Generated by Django 3.2.13 on 2023-06-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membershipservice', '0002_auto_20230621_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersreissuanceform',
            name='imported_raw_materials',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='membersreissuanceform',
            name='locally_sourced_raw_materials',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='membersreissuanceform',
            name='plants',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='membersreissuanceform',
            name='products_manufactured',
            field=models.JSONField(default=dict),
        ),
    ]
