# Generated by Django 3.2.13 on 2023-06-23 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membershipservice', '0004_companiesdeactivationactivationservice_updatefactorylocation_updateonproductmanufactured'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergerOfMemberCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('letter_requesting_merge', models.FileField(blank=True, default=None, null=True, upload_to='letter_requesting_merge/%d/')),
                ('most_recent_finicial_statement', models.FileField(blank=True, default=None, null=True, upload_to='most_recent_finicial_statement/%d/')),
                ('members_reissuanceform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membershipservice.membersreissuanceform')),
            ],
        ),
    ]
