# Generated by Django 3.2.13 on 2023-06-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membershipservice', '0005_mergerofmembercompanies'),
    ]

    operations = [
        migrations.AddField(
            model_name='companiesdeactivationactivationservice',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='companiesthatlostmancert',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mergerofmembercompanies',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='renewalofcertwiththatchangethieroriginialname',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='updatefactorylocation',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='updateonproductmanufactured',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
