# Generated by Django 3.2.13 on 2023-06-28 07:16

from django.db import migrations, models
import membershipservice.models


class Migration(migrations.Migration):

    dependencies = [
        ('membershipservice', '0006_auto_20230623_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersreissuanceform',
            name='imported_raw_materials',
            field=models.JSONField(blank=True, default=membershipservice.models.defualts),
        ),
        migrations.AlterField(
            model_name='membersreissuanceform',
            name='locally_sourced_raw_materials',
            field=models.JSONField(blank=True, default=membershipservice.models.defualts),
        ),
        migrations.AlterField(
            model_name='membersreissuanceform',
            name='plants',
            field=models.JSONField(blank=True, default=membershipservice.models.defualts),
        ),
        migrations.AlterField(
            model_name='membersreissuanceform',
            name='products_manufactured',
            field=models.JSONField(blank=True, default=membershipservice.models.defualts),
        ),
    ]
