# Generated by Django 3.2.13 on 2023-06-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membershipservice', '0007_auto_20230628_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersreissuanceform',
            name='imported_raw_materials',
        ),
        migrations.RemoveField(
            model_name='membersreissuanceform',
            name='locally_sourced_raw_materials',
        ),
        migrations.RemoveField(
            model_name='membersreissuanceform',
            name='plants',
        ),
        migrations.RemoveField(
            model_name='membersreissuanceform',
            name='products_manufactured',
        ),
    ]
