# Generated by Django 3.2.13 on 2023-08-23 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeactivatingDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
                ('is_for_excos', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('month', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeactivatingDue_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_overdue', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paystack_key', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=355)),
                ('re_occuring', models.BooleanField(default=False)),
                ('is_for_excos', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('scheduletype', models.CharField(choices=[('day_of_week', 'Day Of Week'), ('month_of_year', 'Month Of Year')], default='day_of_week', max_length=200)),
                ('schedule', models.JSONField(default=None, null=True)),
                ('alumni_year', models.DateField(blank=True, default=None, null=True)),
                ('is_on_create', models.BooleanField(default=False)),
                ('is_deactivate_users', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Due_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_overdue', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paystack_key', models.TextField(default='')),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dueapp.due')),
            ],
        ),
    ]
